name: OCaml CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2 

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Install Dune
        run: opam install dune

      - name: Build
        run: opam exec -- dune build

      # Run tests
      # - name: Run tests
      #   run: opam exec -- dune runtest
